version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/pablodz/audiosocket"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"